#!/bin/bash

### BEGIN INIT INFO
# Provides:          scriptname
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     3 4 5
# Default-Stop:      0 1 6
# Short-Description: Pi USBDrive Autoplay
# Description:       Raspberry-Pi python script for autoplay video when usbdrive is plugged
### END INIT INFO

case "$1" in
start)
    # Launch Pi USBDrive Autoplay:
    echo "Pi USBDrive Autoplay..."
    /bin/python /home/pi/player.py &>/dev/null &
    echo "End launch"
;;
*)
exit 0
esac